project_id = "tntbjulojatnrqmylorp"

[functions.dr-anacan-chat]
verify_jwt = false

[functions.generate-baby-photo]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-daily-notifications]
verify_jwt = false

[functions.send-bulk-push]
verify_jwt = false

[functions.apple-auth-notifications]
verify_jwt = false

[functions.safety-ai-lookup]
verify_jwt = false

[functions.analyze-cry]
verify_jwt = false

[functions.analyze-poop]
verify_jwt = false

[functions.weather-clothing]
verify_jwt = false
